### PR TITLE
This pull request adds a Function and Class name checker to Peck

### PR DESCRIPTION
**Pull request by raz-iacob**
### What:

- [ ] Bug Fix
- [x] New Feature

### Description:

Adds new functionality to PHP-Peck to analyze PHP code files and spellcheck function and class names against in the current project dictionary. Ignores words and directories that are in the peck.json config.

### CODE REVIEW

**Comment by c0nst4ntin** [comment]
Hey @razvaniacob 👋🏼 

I just saw that we implemented a very similar feature 😅  Really interesting approach with the tokenization. I also tried this, but had problems with anonymous functions without a name. Did you test this and find a way to solve this?

Would love to hear your opinion on my PR and how you think we should proceed with this duplicate feature?
You where first, so I don't want to take anything from you 😄

**Comment by razvaniacob** [comment]
Hwy @c0nst4ntin ,

I didn't test my code with anonymous functions without a name but if your PR is covering that use case, that's awesome!

**Comment by benjam-es** [comment]
I think #19 using reflection might be the way to go

**Comment by raz-iacob** [comment]
@nunomaduro I wached the VOD about this pull request. I didn't have much time when I did this request, but I promise that my next one will be better. I'm happy you went with the one using PHP Reflection. I think that's a good implementation. 

I really like this project and I think it will be a huge success.

**Pull request closed without merging**
